branch-defaults:
  master:
    environment: kpop-dance-inspo-env
    group_suffix: null
environment-defaults:
  kpop-dance-inspo-dev:
    branch: null
    repository: null
global:
  application_name: kpop-dance-inspo
  branch: null
  default_ec2_keyname: null
  default_platform: Python 3.11 running on 64bit Amazon Linux 2023
  default_region: us-west-2
  include_git_submodules: true
  instance_profile: null
  platform_name: null
  platform_version: null
  profile: eb-cli
  repository: null
  sc: git
  workspace_type: Application
